/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CounselorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAcc;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.WorkQueue.BirthMotherCounselor;
import Business.WorkQueue.ParentsToCounsellor;
import javax.swing.JOptionPane;

/**
 *
 * @author naved
 */
public class CounselorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAcc userAccount;
    private int approved = 0;
    private int rejected = 0;
    private int count = 0;
    private int papproved = 0;
    private int prejected = 0;
    private int pcount = 0;
    private EcoSystem system;
    /**
     * Creates new form CounselorWorkArea
     */
    public CounselorWorkAreaJPanel(JPanel userProcessContainer, UserAcc account, Organization organization, Enterprise enterprise ,EcoSystem business) {
        initComponents();
        this.system = business;
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueLabel.setText(organization.getName());
        BirthMotherProgress();
        ParentProgress();
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reviewBirthMotherJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        reviewParentsJButton = new javax.swing.JButton();
        btnNewOrphanage = new javax.swing.JButton();
        Birthmotherprogress = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Birthmotherprogress1 = new javax.swing.JProgressBar();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(26, 26, 29));

        reviewBirthMotherJButton.setBackground(new java.awt.Color(252, 68, 69));
        reviewBirthMotherJButton.setForeground(new java.awt.Color(237, 245, 225));
        reviewBirthMotherJButton.setText("New Birth Mother Applications");
        reviewBirthMotherJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewBirthMotherJButtonActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(237, 245, 225));
        enterpriseLabel.setText("COUNSELOR:");
        enterpriseLabel.setToolTipText("");

        valueLabel.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(237, 245, 225));
        valueLabel.setText("<value>");

        reviewParentsJButton.setBackground(new java.awt.Color(252, 68, 69));
        reviewParentsJButton.setForeground(new java.awt.Color(237, 245, 225));
        reviewParentsJButton.setText("New Parent Applications");
        reviewParentsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewParentsJButtonActionPerformed(evt);
            }
        });

        btnNewOrphanage.setBackground(new java.awt.Color(252, 68, 69));
        btnNewOrphanage.setForeground(new java.awt.Color(237, 245, 225));
        btnNewOrphanage.setText("New Orphanage Applications");
        btnNewOrphanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrphanageActionPerformed(evt);
            }
        });

        Birthmotherprogress.setStringPainted(true);

        jLabel1.setForeground(new java.awt.Color(237, 245, 225));
        jLabel1.setText("Approved:");

        jLabel2.setForeground(new java.awt.Color(237, 245, 225));
        jLabel2.setText("Pending:");

        jLabel3.setForeground(new java.awt.Color(237, 245, 225));
        jLabel3.setText("Rejected:");

        jLabel4.setForeground(new java.awt.Color(237, 245, 225));
        jLabel4.setText("jLabel4");

        jLabel5.setForeground(new java.awt.Color(237, 245, 225));
        jLabel5.setText("jLabel4");

        jLabel6.setForeground(new java.awt.Color(237, 245, 225));
        jLabel6.setText("jLabel4");

        jLabel7.setForeground(new java.awt.Color(237, 245, 225));
        jLabel7.setText("Birth Mother Application Progress");

        jLabel8.setForeground(new java.awt.Color(237, 245, 225));
        jLabel8.setText("jLabel4");

        jLabel9.setForeground(new java.awt.Color(237, 245, 225));
        jLabel9.setText("Parent Application Progress");

        Birthmotherprogress1.setStringPainted(true);

        jLabel10.setForeground(new java.awt.Color(237, 245, 225));
        jLabel10.setText("Approved:");

        jLabel11.setForeground(new java.awt.Color(237, 245, 225));
        jLabel11.setText("Pending:");

        jLabel12.setForeground(new java.awt.Color(237, 245, 225));
        jLabel12.setText("Rejected:");

        jLabel13.setForeground(new java.awt.Color(237, 245, 225));
        jLabel13.setText("jLabel4");

        jLabel14.setForeground(new java.awt.Color(237, 245, 225));
        jLabel14.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(reviewBirthMotherJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reviewParentsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNewOrphanage, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(102, 102, 102)
                                    .addComponent(jLabel9))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Birthmotherprogress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Birthmotherprogress1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(43, 43, 43))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel13)
                                    .addGap(25, 25, 25)
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel14)
                                    .addGap(13, 13, 13)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reviewBirthMotherJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(reviewParentsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnNewOrphanage, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Birthmotherprogress, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(3, 3, 3)
                        .addComponent(Birthmotherprogress1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reviewBirthMotherJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewBirthMotherJButtonActionPerformed
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("BirthMotherRequestWorkAreaJPanel", new BirthMotherRequestWorkAreaJPanel(userProcessContainer, userAccount, organization, enterprise));
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_reviewBirthMotherJButtonActionPerformed

    private void reviewParentsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewParentsJButtonActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ParentsRequestWorkAreaJPanel", new ParentsRequestWorkAreaJPanel(userProcessContainer, userAccount, organization, enterprise,system));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_reviewParentsJButtonActionPerformed

    private void btnNewOrphanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrphanageActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("OrphanageRequestWorkAreaPanel", new OrphanageRequestWorkAreaPanel(userProcessContainer));
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnNewOrphanageActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Birthmotherprogress;
    private javax.swing.JProgressBar Birthmotherprogress1;
    private javax.swing.JButton btnNewOrphanage;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton reviewBirthMotherJButton;
    private javax.swing.JButton reviewParentsJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

    private void ParentProgress() {
        
    
               try{
            for (ParentsToCounsellor request : enterprise.getWorkQueue().getParentCounselor()){

                if ("Completed".equals(request.getStatus())){
                        papproved++;
                }
                if ("Rejected".equals(request.getStatus())){
                        prejected++;
                }
            pcount++;
            
            
            
            
        }   
            if (pcount != 0){
            float percentage = ((float)(papproved)/pcount)*100;
            Birthmotherprogress1.setValue((int) percentage);}
            else {
                Birthmotherprogress1.setValue(0);
            }
            jLabel13.setText(String.valueOf(papproved));
            jLabel14.setText(String.valueOf(prejected));
            jLabel8.setText(String.valueOf(pcount - (papproved+prejected)));
       }
    catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error1");
        }
}
    private void BirthMotherProgress() {
        
    
               try{
            for (BirthMotherCounselor request : enterprise.getWorkQueue().getBirthMotherToCounsellor()){
            if(request.getCounsellor().getEmpName().equals(userAccount.getCounselor().getEmpName())){
                if ("Completed".equals(request.getStatus())){
                        approved++;
                }
                if ("Rejected".equals(request.getStatus())){
                        rejected++;
                }
            count++;
            
            }
            
            
        }  
            if (count != 0){
            float percentage = ((float)(approved)/count)*100;
            Birthmotherprogress.setValue((int) percentage);}
            else {
                Birthmotherprogress.setValue(0);
            }
            
            jLabel4.setText(String.valueOf(approved));
            jLabel5.setText(String.valueOf(rejected));
            jLabel6.setText(String.valueOf(count - (approved+rejected)));
       }
    catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error");
        }
}
}
